language: node_js
node_js:
  - 'node'

# Uncomment when using awesome-lint, https://github.com/sindresorhus/awesome-lint/pull/67
# git:
#   depth: false

before_install:
  - rvm install 2.2.2

install:
  # - npm install --global awesome-lint
  - gem install awesome_bot

script:
  # - awesome-lint README.md
  - awesome_bot README.md --allow-redirect --allow-dupe

notifications:
  email:
    on_failure: always
