name: Check Links

on:
  push:
    branches:
    - master
    - action
  pull_request:
    branches:
      - master
  schedule:
    # Runs every midnight
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.4'
    - run: gem install awesome_bot
    - run: awesome_bot README.md --allow-redirect --allow-dupe --set-timeout 60
